name: amphora-buildstream-sdk
min-version: 2.7
element-path: elements

plugins:
- origin: pip
  package-name: buildstream-plugins-community
  sources:
  - zip

aliases:
  ubuntu: https://cdimage.ubuntu.com/ubuntu-base/releases/24.04/release/
  google-android: https://dl.google.com/android/repository/
  llvm-mingw: https://github.com/bylaws/llvm-mingw/releases/download/
  sdk-release: https://github.com/amphora-dev/buildstream-sdk/releases/download/

variables:
  ndk-root: /opt/android-ndk
  ndk-toolchain: "%{ndk-root}/toolchains/llvm/prebuilt/linux-x86_64"
